---
title: "Analysis & Hypotheses"
pagetitle: 'Analysis & Hypotheses'
output: 
  html_document: 
    css: "styles.css"
    toc: true
    toc_float:
      collapsed: false
---

```{r htmltools_code, include=FALSE}
htmltools::tagList(rmarkdown::html_dependency_font_awesome())

```
## Summary

We want to analyze the housing sales prices to analyze which variables influence the sales price the most. We also want to train a model that predicts the sales price of a house given the variables necessary, which will be completed under the [Modeling Page](/modeling)

To begin our analysis of the data we will create correlation matrices, visualize individual variables, and look at ANOVA outputs to see which variables appear to contribute the most to predicting sales price.

## Importing Libraries + Loading Data

```{R imports, message=FALSE}
library(dplyr)
library(tidyr)
library(ggplot2)
library(readr)
library(tidyverse)
#install.packages("corrplot")
library(corrplot)
data <- read_csv("~/SDS322E/final_project_homepage/clean_train.csv")
data <- na.omit(data)
head(data)

```

# Visualization

### Histogram of SalePrice (dependent variable):

```{R sale_price_histogram}


data %>% 
  ggplot(aes(x=SalePrice)) +
  geom_histogram(color = "#000000", fill = "#0099F8") + 
  labs(
    title = "Histogram of SalesPrice in Housing Data",
    caption = "Source: fill me in",
    x = "Sales Price in $USD",
    y = "Count"
  ) +
  theme_classic() +
  theme(
    plot.title = element_text(color = "#0099F8", size = 16, face = "bold"),
    plot.subtitle = element_text(size = 10, face = "bold"),
    plot.caption = element_text(face = "italic")
  )
head(data)
```

As you can see, the sales price of the homes is slightly right-skewed
### Correlation Plot of numeric variables
```{R correlation_plot}
# Get only the numeric data
numeric_only <- data %>% select_if(is.numeric)
res <- cor(numeric_only)
#res %>% pivot_longer(c(0,10), names_to = "var2")

corrplot(res, tl.cex = .5)
```
TODO : create some sort of analysis of the categorical variables

```{R}
# Get only the categorical data
categorical <- data %>% select_if(negate(is.numeric))
categorical %>% glimpse()

data$MSSubClass <- as.factor(data$MSSubClass)
data$MSZoning <- as.factor(data$MSZoning)
data$Street <- as.factor(data$Street)
data$Alley <- as.factor(data$Alley)
data$LotShape <-  as.factor(data$LotShape)
data$LandContour <- as.factor(data$LandContour)
data$Utilities <- as.factor(data$Utilities)
data$LotConfig <-  as.factor(data$LotConfig)
data$LandSlope <-  as.factor(data$LandSlope)
data$Neighborhood <-  as.factor(data$Neighborhood)
data$Condition1 <- as.factor(data$Condition1)
data$Condition2 <- as.factor(data$Condition2)
data$BldgType <- as.factor(data$BldgType)
data$HouseStyle <- as.factor(data$HouseStyle)
data$RoofStyle <- as.factor(data$RoofStyle)
data$RoofMatl <- as.factor(data$RoofMatl)
data$Exterior1st <- as.factor(data$Exterior1st)
data$Exterior2nd <- as.factor(data$Exterior2nd)
data$MasVnrType <- as.factor(data$MasVnrType)
data$ExterQual <- as.factor(data$ExterQual)
data$ExterCond <- as.factor(data$ExterCond)
data$Foundation <- as.factor(data$Foundation)
data$BsmtQual <- as.factor(data$BsmtQual)
data$BsmtCond <- as.factor(data$BsmtCond)
data$BsmtExposure <- as.factor(data$BsmtExposure)
data$BsmtFinType1 <- as.factor(data$BsmtFinType1)
data$BsmtFinType2 <- as.factor(data$BsmtFinType2)
data$Heating <- as.factor(data$Heating)
data$HeatingQC <- as.factor(data$HeatingQC)
data$CentralAir <- as.factor(data$CentralAir)
data$Electrical <- as.factor(data$Electrical)
data$KitchenQual <- as.factor(data$KitchenQual)
data$Functional <- as.factor(data$Functional)
data$FireplaceQu <- as.factor(data$FireplaceQu)
data$GarageType <- as.factor(data$GarageType)
data$GarageFinish  <- as.factor(data$GarageFinish)
data$GarageQual  <- as.factor(data$GarageQual)
data$GarageCond  <- as.factor(data$GarageCond)
data$PavedDrive <- as.factor(data$PavedDrive)
data$PoolQC <- as.factor(data$PoolQC)
data$Fence <- as.factor(data$Fence)
data$MiscFeature <- as.factor(data$MiscFeature)
data$SaleType <- as.factor(data$SaleType)
data$SaleCondition <- as.factor(data$SaleCondition)

factorial_variables <- c(2,3,6:17,22:26,28:34,36,40:43,54,56,58,59,61,64:66,73:75,79,80)
str(data[,factorial_variables])

library(dplyr)
library(tidyr)
data %>%
  gather(Attributes, value, factorial_variables[1:9]) %>%
  ggplot(aes(x=value, fill=Attributes)) +
  geom_bar(stat="count", show.legend = F) +
  facet_wrap(~Attributes, scales="free_x") +
  labs(x="Values", y="Frequency",
       title="Categorical Variables - Bar graphs") +
  scale_fill_discrete()
data %>%
  gather(Attributes, value, factorial_variables[10:18]) %>%
  ggplot(aes(x=value, fill=Attributes)) +
  geom_bar(stat="count", show.legend = F) +
  facet_wrap(~Attributes, scales="free_x") +
  labs(x="Values", y="Frequency",
       title="Categorical Variables - Bar graphs") +
  scale_fill_discrete() 
data %>%
  gather(Attributes, value, factorial_variables[28:36]) %>%
  ggplot(aes(x=value, fill=Attributes)) +
  geom_bar(stat="count", show.legend = F) +
  facet_wrap(~Attributes, scales="free_x") +
  labs(x="Values", y="Frequency",
       title="Categorical Variables - Bar graphs") +
  scale_fill_discrete()

data %>%
  gather(Attributes, value, factorial_variables[37:44]) %>%
  ggplot(aes(x=value, fill=Attributes)) +
  geom_bar(stat="count", show.legend = F) +
  facet_wrap(~Attributes, scales="free_x") +
  labs(x="Values", y="Frequency",
       title="Categorical Variables - Bar Graphs") +
  scale_fill_discrete() 

data$MSSubClass <- as.factor(data$MSSubClass)
data$MSZoning <- as.factor(data$MSZoning)
data$Street <- as.factor(data$Street)
data$Alley <- as.factor(data$Alley)
data$LotShape <-  as.factor(data$LotShape)
data$LandContour <- as.factor(data$LandContour)
data$Utilities <- as.factor(data$Utilities)
data$LotConfig <-  as.factor(data$LotConfig)
data$LandSlope <-  as.factor(data$LandSlope)
data$Neighborhood <-  as.factor(data$Neighborhood)
data$Condition1 <- as.factor(data$Condition1)
data$Condition2 <- as.factor(data$Condition2)
data$BldgType <- as.factor(data$BldgType)
data$HouseStyle <- as.factor(data$HouseStyle)
data$RoofStyle <- as.factor(data$RoofStyle)
data$RoofMatl <- as.factor(data$RoofMatl)
data$Exterior1st <- as.factor(data$Exterior1st)
data$Exterior2nd <- as.factor(data$Exterior2nd)
data$MasVnrType <- as.factor(data$MasVnrType)
data$ExterQual <- as.factor(data$ExterQual)
data$ExterCond <- as.factor(data$ExterCond)
data$Foundation <- as.factor(data$Foundation)
data$BsmtQual <- as.factor(data$BsmtQual)
data$BsmtCond <- as.factor(data$BsmtCond)
data$BsmtExposure <- as.factor(data$BsmtExposure)
data$BsmtFinType1 <- as.factor(data$BsmtFinType1)
data$BsmtFinType2 <- as.factor(data$BsmtFinType2)
data$Heating <- as.factor(data$Heating)
data$HeatingQC <- as.factor(data$HeatingQC)
data$CentralAir <- as.factor(data$CentralAir)
data$Electrical <- as.factor(data$Electrical)
data$KitchenQual <- as.factor(data$KitchenQual)
data$Functional <- as.factor(data$Functional)
data$FireplaceQu <- as.factor(data$FireplaceQu)
data$GarageType <- as.factor(data$GarageType)
data$GarageFinish  <- as.factor(data$GarageFinish)
data$GarageQual  <- as.factor(data$GarageQual)
data$GarageCond  <- as.factor(data$GarageCond)
data$PavedDrive <- as.factor(data$PavedDrive)
data$PoolQC <- as.factor(data$PoolQC)
data$Fence <- as.factor(data$Fence)
data$MiscFeature <- as.factor(data$MiscFeature)
data$SaleType <- as.factor(data$SaleType)
data$SaleCondition <- as.factor(data$SaleCondition)

factorial_variables <- c(2,3,6:17,22:26,28:34,36,40:43,54,56,58,59,61,64:66,73:75,79,80)
str(data[,factorial_variables])

library(dplyr)
library(tidyr)
data %>%
  gather(Attributes, value, factorial_variables[1:9]) %>%
  ggplot(aes(x=value, fill=Attributes)) +
  geom_bar(stat="count", show.legend = F) +
  facet_wrap(~Attributes, scales="free_x") +
  labs(x="Values", y="Frequency",
       title="Categorical Variables - Bar graphs") +
  scale_fill_discrete()
data %>%
  gather(Attributes, value, factorial_variables[10:18]) %>%
  ggplot(aes(x=value, fill=Attributes)) +
  geom_bar(stat="count", show.legend = F) +
  facet_wrap(~Attributes, scales="free_x") +
  labs(x="Values", y="Frequency",
       title="Categorical Variables - Bar graphs") +
  scale_fill_discrete() 
data %>%
  gather(Attributes, value, factorial_variables[28:36]) %>%
  ggplot(aes(x=value, fill=Attributes)) +
  geom_bar(stat="count", show.legend = F) +
  facet_wrap(~Attributes, scales="free_x") +
  labs(x="Values", y="Frequency",
       title="Categorical Variables - Bar graphs") +
  scale_fill_discrete()

data %>%
  gather(Attributes, value, factorial_variables[37:44]) %>%
  ggplot(aes(x=value, fill=Attributes)) +
  geom_bar(stat="count", show.legend = F) +
  facet_wrap(~Attributes, scales="free_x") +
  labs(x="Values", y="Frequency",
       title="Categorical Variables - Bar Graphs") +
  scale_fill_discrete() 

```

## TODO: ANOVA 
Create some sort of analysis of variance

# Hypotheses

Now we have visualized our data, we can make some hypotheses

##  Hypothesis 1 
Houses with an overall quality rating greater than 5 have on average a higher sales price.
```{R hypothesis-1}
hyp1<-data %>%
  mutate(quality = case_when(
    (OverallQual<=5) ~ "lower quality",
    (OverallQual>5) ~ "higher quality"
    ))
t.test(SalePrice ~ quality, data = hyp1,
        var.equal = FALSE, alternative = "greater")
boxplot(SalePrice ~ quality, data = hyp1, xlab = "Quality Level",
   ylab = "Sales Price ($)", main = "Comparing Sales price of different Quality houses")
```
The one tailed t-test reveals that the there is a significant difference between the means of higher quality houses(quality>5) and lower quality houses(Overall quality <=5). Since the p-value is less than 0.05, we can reject the null hypothesis and accept the alternative that higher quality houses have a higher sales price.

## Hypothesis 2
There is a significant difference in sale price of houses that have a foundation made of poured concrete vs. houses that have a foundation made of cinder blocks.
```{R hypothesis2}
data1<-data %>%
select(SalePrice, Foundation) %>%
  filter(Foundation=='PConc'|Foundation=='CBlock')
AOV<-aov(SalePrice~Foundation,data=data1)
summary(AOV)

summ<-data1%>% group_by(Foundation)%>% summarise(mean_price=mean(SalePrice))
ggplot(summ,aes(x=Foundation,y=mean_price))+geom_col()+labs(y="Mean Sales Price ($)",x="Foundation Type")+ggtitle("Mean Sales Price of Houses Varying in Foundation")

```
Based on the ANOVA test, we can conclude that there is a significant difference in sales price between houses that have foundations made of poured concrete and houses that have cinder blocks.

## Hypothesis 3
There is a significant difference in sale price of houses that have finished garages (3) vs those houses that have unfinished garages (1).
```{R hypothesis3}
data2<-data %>%
select(SalePrice, GarageFinish) %>%
  filter(GarageFinish=='1'|GarageFinish=='3')
AOV1<-aov(SalePrice~GarageFinish,data=data2)
summary(AOV1)

summ<-data2%>% group_by(GarageFinish)%>% summarise(mean_price=mean(SalePrice))
ggplot(summ,aes(x=GarageFinish,y=mean_price))+geom_col()+labs(y="Mean Sales Price ($)",x="Garage Finish")+ggtitle("Mean Sales Price of Houses Varying in Garage")

```
Based on the ANOVA test, we can conclude that there is a significant difference in sales price between houses that have unfinished garages and houses that have finished garages.

## Hypothesis 4
Houses with a garage that can hold 3 or more cars have on average a higher sales price.
```{R hypothesis4}
hyp4<-data %>%
  mutate(garagecarsn = case_when(
    (GarageCars<3) ~ "less than 3 cars",
    (GarageCars>=3) ~ "3 or more cars"
    ))
t.test(SalePrice ~ garagecarsn, data = hyp4,
        var.equal = FALSE, alternative = "greater")
boxplot(SalePrice ~ garagecarsn, data = hyp4, xlab = "Car Capacity",
   ylab = "Sales Price ($)", main = "Comparing Sales price with Different Garage capacity")
```

The one tailed t-test reveals that the there is a significant difference between the means of houses that have garages of 3 or more car capacity and houses that have garages with less than 3 car capacity. Since the p-value is less than 0.05, we can reject the null hypothesis and accept the alternative that higher quality houses have a higher sales price.


